// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5053.RobotBuilderLisa.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc5053.RobotBuilderLisa.Robot;
import org.usfirst.frc5053.RobotBuilderLisa.RobotMap;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 *
 */
public class PrintRobotDistance extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public PrintRobotDistance() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	System.out.println("Robot.Distance="+Robot.driveTrain.the_driveTrainMotionControl.GetAverageDistance()+", "+
    			           "Robot.LeftDistance="+Robot.driveTrain.the_driveTrainMotionControl.GetLeftDistance()+", "+
    			           "Robot.RightDistance="+Robot.driveTrain.the_driveTrainMotionControl.GetRightDistance()
    			          );
    	
		SmartDashboard.putNumber("Robot Distance",Robot.driveTrain.the_driveTrainMotionControl.GetAverageDistance()); 
		SmartDashboard.putNumber("Robot Left Distance",Robot.driveTrain.the_driveTrainMotionControl.GetLeftDistance()); 
		SmartDashboard.putNumber("Robot Right Distance",Robot.driveTrain.the_driveTrainMotionControl.GetRightDistance()); 
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
