// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5053.RobotBuilderLisa.subsystems;

import org.usfirst.frc5053.RobotBuilderLisa.Robot;
import org.usfirst.frc5053.RobotBuilderLisa.RobotMap;
import org.usfirst.frc5053.RobotBuilderLisa.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.Talon;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.ADXRS450_Gyro;

import org.usfirst.frc5053.RobotBuilderLisa.subsystems.DriveTrainMotionControl;


/**
 *
 */
public class DriveTrain extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final Encoder rightDriveEncoder = RobotMap.driveTrainrightDriveEncoder;
    private final Encoder leftDriveEncoder = RobotMap.driveTrainleftDriveEncoder;
    private final SpeedController leftDrive1PWM = RobotMap.driveTrainleftDrive1PWM;
    private final SpeedController leftDrive2PWM = RobotMap.driveTrainleftDrive2PWM;
    private final SpeedControllerGroup leftMotors = RobotMap.driveTrainleftMotors;
    private final SpeedController rightDrive2PWM = RobotMap.driveTrainrightDrive2PWM;
    private final SpeedController rightDrive1PWM = RobotMap.driveTrainrightDrive1PWM;
    private final SpeedControllerGroup rightMotors = RobotMap.driveTrainrightMotors;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final ADXRS450_Gyro gyro = RobotMap.gyro;
    

    public DriveTrainMotionControl the_driveTrainMotionControl = new DriveTrainMotionControl(leftMotors, rightMotors, leftDriveEncoder, rightDriveEncoder,gyro); 
    		@Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new DriveTeleop());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }



}

